[1;35m[WARNING]: No inventory was parsed, only implicit localhost is available[0m
[1;35m[WARNING]: provided hosts list is empty, only localhost is available. Note that[0m
[1;35mthe implicit localhost does not match 'all'[0m

PLAY [Сбор информации о созданных виртуальных машинах в oVirt] *****************

TASK [Аутентификация в oVirt] **************************************************
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: ovirtsdk4.Error: The CA file '/home/morozovms/NPIS/backend/pki-resource.crt' doesn't exist[0m
[0;31mfatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1734773059.6977851-16872-220140790046833/AnsiballZ_ovirt_auth.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1734773059.6977851-16872-220140790046833/AnsiballZ_ovirt_auth.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1734773059.6977851-16872-220140790046833/AnsiballZ_ovirt_auth.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ovirt.ovirt.plugins.modules.ovirt_auth', init_globals=dict(_module_fqn='ansible_collections.ovirt.ovirt.plugins.modules.ovirt_auth', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_ovirt.ovirt.ovirt_auth_payload_8wvfwe0t/ansible_ovirt.ovirt.ovirt_auth_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_auth.py\", line 311, in <module>\n  File \"/tmp/ansible_ovirt.ovirt.ovirt_auth_payload_8wvfwe0t/ansible_ovirt.ovirt.ovirt_auth_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_auth.py\", line 274, in main\n  File \"/NPIS/venv/lib/python3.12/site-packages/ovirtsdk4/__init__.py\", line 308, in __init__\n    raise Error('The CA file \\'%s\\' doesn\\'t exist' % ca_file)\novirtsdk4.Error: The CA file '/home/morozovms/NPIS/backend/pki-resource.crt' doesn't exist\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}[0m

PLAY RECAP *********************************************************************
[0;31mlocalhost[0m                  : ok=0    changed=0    unreachable=0    [0;31mfailed=1   [0m skipped=0    rescued=0    ignored=0   
